# Generated by Django 2.0.1 on 2018-02-03 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
