# Generated by Django 2.0.1 on 2018-02-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0003_answer_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
