# Generated by Django 2.0.1 on 2018-02-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0005_auto_20180209_0613'),
        ('so_endpoint', '0005_profile'),
    ]

    operations = [
    ]
