# Generated by Django 2.0.1 on 2018-02-11 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0007_auto_20180211_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
