# Generated by Django 2.0.1 on 2018-02-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0008_auto_20180211_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='so_endpoint.Answer'),
        ),
    ]
