# Generated by Django 2.0.1 on 2018-02-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0010_auto_20180211_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='accepted_answer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_answer_set', to='so_endpoint.Answer'),
        ),
    ]
