# Generated by Django 2.0.1 on 2018-03-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_head',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
